# Generated by Django 5.0.6 on 2024-07-30 15:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Web", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="rental_price",
        ),
    ]
